package spittr.mail;

import org.apache.velocity.exception.VelocityException;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.core.io.ClassPathResource;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import spittr.mail.domain.Spitter;
import spittr.mail.domain.Spittle;

import javax.mail.MessagingException;
import java.util.Date;

/**
 * Created by wenda on 8/25/2017.
 */
@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(classes=MailConfig.class)
public class MailTest {

    @Autowired
    SpittleMailService spittleMailService;
//
//    @Autowired
//    JavaMailSender mailSender;

    @Test
    public void testSendSimpleEmail() {
        System.out.println(spittleMailService);
//        System.out.println(mailSender);
        Spitter spitter = new Spitter(1L, null, "daniel", "Daniel Wen", "daniel.wen@ericsson.com", true );
        Spittle spittle = new Spittle(1L, spitter, "A test spittle from spring mail sender", new Date());
        spittleMailService.sendSimpleSpittleEmail("wendaniel@hotmail.com", spittle);
    }

    @Test
    public void testSendEmailWithAttachment() throws MessagingException {
        Spitter spitter = new Spitter(1L, null, "daniel", "Daniel Wen", "daniel.wen@ericsson.com", true );
        Spittle spittle = new Spittle(1L, spitter, "A test spittle with attachment", new Date());
        spittleMailService.sendSpittleEmailWithAttachment("wendaniel@hotmail.com", spittle);
    }

    @Test
    public void testSendRichSpittleEmail() throws MessagingException {
        Spitter spitter = new Spitter(1L, null, "daniel", "Daniel Wen", "daniel.wen@ericsson.com", true );
        Spittle spittle = new Spittle(1L, spitter, "A test spittle using html and inline image", new Date());
        spittleMailService.sendRichSpittleEmail("wendaniel@hotmail.com", spittle);
    }

    @Test
    public void testSendRichSpittleEmailGeneratedByVelocity() throws MessagingException, VelocityException {
        Spitter spitter = new Spitter(1L, null, "daniel", "Daniel Wen", "daniel.wen@ericsson.com", true );
        Spittle spittle = new Spittle(1L, spitter, "A test spittle generated by velocity template engine", new Date());
        spittleMailService.sendRichSpittleEmailGeneratedByVelocity("wendaniel@hotmail.com", spittle);
    }

    @Test
    public void testSendRichSpittleEmailGeneratedByThymleaf() throws MessagingException, VelocityException {
        Spitter spitter = new Spitter(1L, null, "daniel", "Daniel Wen", "daniel.wen@ericsson.com", true );
        Spittle spittle = new Spittle(1L, spitter, "A test spittle generated by Thymleaf template engine", new Date());
        spittleMailService.sendRichSpittleEmailGeneratedByThymleaf("wendaniel@hotmail.com", spittle);
    }

}
